{{- if and (eq .Values.auth.strategy "basic") .Values.auth.basic.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "network-observer.basicAuthSecretName" . }}
  labels:
    {{- include "network-observer.labels" . | nindent 4 }}
stringData:
  htpasswd: |-
    {{- .Values.auth.basic.htpasswd | nindent 4}}
{{- end }}
