{{- $createBasicAuth := (and (.Values.auth.basic.create) (eq .Values.auth.strategy "basic")) }}
{{- $createSessionAuth := (and (.Values.auth.openshift.createCookieSecret) (eq .Values.auth.strategy "openshift")) }}
{{- if or $createSessionAuth $createBasicAuth }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "network-observer.setupJobName" . }}
  labels:
    {{- include "network-observer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        {{- include "network-observer.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "network-observer.setupJobName" . }}
      restartPolicy: Never
      containers:
      {{- if $createSessionAuth }}
      - name: init-session-cookie
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args:
          - "ensure-secret"
          - "-format=oauth2-proxy-session-cookie"
          - {{ include "network-observer.sessionCookieSecretName" . }}
      {{- end }}
      {{- if $createBasicAuth }}
      - name: init-basic-auth-secret
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args:
          - "ensure-secret"
          - "-format=htpasswd"
          - {{ include "network-observer.basicAuthSecretName" . }}
      {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "network-observer.setupJobName" . }}
  labels:
    {{- include "network-observer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind : Role
metadata:
  labels:
    {{- include "network-observer.labels" . | nindent 4 }}
  name: {{ include "network-observer.setupJobName" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "network-observer.labels" . | nindent 4 }}
  name: {{ include "network-observer.setupJobName" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ include "network-observer.setupJobName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "network-observer.setupJobName" . }}
{{- end }}
