---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "network-observer.nginxConfigMapName" . }}
  labels:
    {{- include "network-observer.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes auto;
    pid /tmp/nginx.pid;
    
    events {}
    http {
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;
    
        server {
            listen              8443 ssl;
            keepalive_timeout   70;
    
            ssl_certificate     /etc/certificates/tls.crt;
            ssl_certificate_key /etc/certificates/tls.key;
            ssl_protocols       TLSv1.3;
            add_header Strict-Transport-Security "max-age=63072000" always;
            
            {{- if eq .Values.auth.strategy "basic" }}
            location /api/ {
              auth_basic           "Skupper";
              auth_basic_user_file /etc/httpusers/htpasswd;
              proxy_pass  http://localhost:8080;
            }
            {{- end }}
            location / {
              proxy_pass  http://localhost:8080;
            }
        }
    }

