apiVersion: v1
kind: Service
metadata:
  name: {{ include "network-observer.fullname" . }}
  labels:
    {{- include "network-observer.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.tls.openshiftIssued }}
    service.beta.openshift.io/serving-cert-secret-name: {{ include "network-observer.tlsSecretName" . }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "network-observer.selectorLabels" . | nindent 4 }}
