---
apiVersion: v1
data:
  name: other
  ingress: none
  console-authentication: unsecured
kind: ConfigMap
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  name: skupper-site
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skupper-service-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skupper-service-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skupper-service-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skupper-service-controller
subjects:
- kind: ServiceAccount
  name: skupper-service-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-service-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      skupper.io/component: service-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: skupper-service-controller
        app.kubernetes.io/part-of: skupper
        skupper.io/component: service-controller
    spec:
      containers:
      - name: service-controller
        image: quay.io/gordons/service-controller
      serviceAccount: skupper-service-controller
      serviceAccountName: skupper-service-controller

